<li class="content column-num3">
    
    
    <div class="pic">
					<a href="[field:arcurl/]"  title="[field:title/]" target="_self">
                                <img src= "[field:litpic/]"  alt= "[field:title/]" title= "[field:title/]" /></a>
	</div>
	 
            <div class="main">
				<div class="newstitle">
					<ul>
						<li class="title">
							<h3>
							<a href="[field:arcurl/]"  title="field:title/" target="_self">
												[field:title/]</a>
										</h3>
						</li>
						</ul>
				</div>
				<div class="newslist">
					<ul>
						</ul>
				</div>
				</div>
      </li>