<?php
$z[0]=Array("field","",285,304);
$z[0][4]['name']="title";
$z[1]=Array("global","",305,331);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",799,836);
$z[2][4]['filename']="header.htm";
$z[3]=Array("include","",844,882);
$z[3][4]['filename']="header2.htm";
$z[4]=Array("channel","\r\n                            <li class=\"menu-none\"><a id=\"comContent2_7\" href=\"[field:typeurl/]\" title=\"[field:typename/]\" class=\"menu-text1\" >[field:typename/]</a></li>\r\n	                        ",2078,2313);
$z[4][4]['type']="son";
$z[5]=Array("include","",2428,2471);
$z[5][4]['filename']="sidebarslide.htm";
$z[6]=Array("field","",2853,2882);
$z[6][4]['name']="position";
$z[7]=Array("field","",3672,3693);
$z[7][4]['name']="content";
$z[8]=Array("include","",3931,3968);
$z[8][4]['filename']="footer.htm";

?>