<li class="content column-num4">
					
                    
                    <div class="pic-module">
						<div class="pic">
								<a class="FrontProducts_list01-1434951196979_lightbx" data-fancybox-group="FrontProducts_list01-1434951196979_gallery" href="[field:arcurl/]"  title="[field:title/]">
										<img src= "[field:litpic/]"  id= "FrontProducts_list01-1434951196979_59" alt= "[field:title/]" title= "[field:title/]" onerror= "this.src='/templets/default/images/common/noimage.jpg'" /></a>
								</div>
							<script type="text/javascript">							
									$('.FrontProducts_list01-1434951196979_lightbx').lightBox();
								</script>
						</div>
					<div class="pro-module">
						<ul class="basic">
							<li class="code">
									<h1>
										<span>商品名称：</span>
										<strong>											
												<a href="[field:arcurl/]" 
												title="[field:title/]"
												target="_self"
												>																				
												[field:title/]</a>
										</strong>
									</h1>
									</li>
								</ul>
						<p class="buttonP">
							</p>
						</div>
				</li>

				<li class="clearBoth"></li>