<field:brand itemname="商品名称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
	
</field:brand>
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:uptime>	
	
<field:units itemname="酒精度" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="250" page="">
	
</field:units>
		
<field:vocation itemname="净含量" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
	
</field:vocation>
	
<field:infotype itemname="香型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
	
</field:infotype>
	
<field:trueprice itemname="浏览次数" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">
	
</field:trueprice>
<field:price itemname="零售价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">
	
</field:price>
<field:body itemname="商品详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
	
</field:body>
	
	
<field:tupian itemname="商品图片" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tupian>
