<li class="content column-num3">
					<div class="pic-module">
						<div class="pic">
									<a href="[field:arcurl/]" 
										title="[field:title/]" target="_self">
											<img src= "[field:litpic/]"  id= "FrontProducts_list01-1434963925335_29" alt= "[field:title/]" title= "[field:title/]" onerror= "this.src='/templets/default/images/common/noimage.jpg'" /></a>
								</div>
							</div>
					<div class="pro-module">
						<ul class="basic">
							<li class="code">
									<h1>
										<span>商品名称：</span>
										<strong>
											<a href="[field:arcurl/]" 
												title="field:title/"
												target="_self"
												>
												[field:title/]</a>
										</strong>
									</h1>
									</li>
								</ul>
						<p class="buttonP">
							</p>
						</div>
				</li>