<?php
$z[0]=Array("type"," <a href=\"[field:typelink/]\" rel=\"summenu_FrontColumns_navigation01-1434078754918_54\" title=\"[field:typename/]\">[field:typename/]</a> ",2634,2800);
$z[0][4]['typeid']="1";
$z[1]=Array("type"," <a href=\"[field:typeurl/]\"  title=\"[field:typename/]\"> [field:typename/]</a> ",2826,2936);
$z[1][4]['typeid']="7";
$z[2]=Array("type"," <a href=\"[field:typeurl/]\"  title=\"[field:typename/]\"> [field:typename/]</a> ",2962,3072);
$z[2][4]['typeid']="8";
$z[3]=Array("type"," <a href=\"[field:typeurl/]\"  title=\"[field:typename/]\"> [field:typename/]</a> ",3098,3208);
$z[3][4]['typeid']="9";
$z[4]=Array("type"," <a href=\"[field:typeurl/]\"  title=\"[field:typename/]\"> [field:typename/]</a> ",3234,3345);
$z[4][4]['typeid']="11";
$z[5]=Array("type"," <a href=\"[field:typeurl/]\"  title=\"[field:typename/]\"> [field:typename/]</a> ",3371,3482);
$z[5][4]['typeid']="12";
$z[6]=Array("type"," <a href=\"[field:typeurl/]\"  title=\"[field:typename/]\"> [field:typename/]</a> ",3508,3619);
$z[6][4]['typeid']="13";
$z[7]=Array("channel","\r\n          <li> <a href=\"[field:typeurl/]\" > [field:typename/]</a> </li>\r\n          ",3799,3931);
$z[7][4]['type']="son";
$z[7][4]['typeid']="1";

?>