<?php
$z[0]=Array("field","",305,324);
$z[0][4]['name']="title";
$z[1]=Array("global","",325,351);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",392,414);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",454,505);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",992,1029);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",1037,1075);
$z[5][4]['filename']="header2.htm";
$z[6]=Array("channel","\r\n      <li class=\"menu-none\">\r\n			<a href=\"[field:typeurl/]\"  target=\"_self\" class=\"menu-text1\">\r\n				[field:typename/]</a>\r\n       </li>\r\n    ",3803,3985);
$z[6][4]['type']="son";
$z[7]=Array("include","",4094,4137);
$z[7][4]['filename']="sidebarslide.htm";
$z[8]=Array("field","",4530,4559);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n    <li class=\"content column-num1\">\r\n 	<div class=\"newstitle\">\r\n				<ul>\r\n					<li class=\"title\">\r\n						<h3>\r\n						<a href=\"[field:arcurl/]\"  title=\"“[field:title/]\" target=\"_self\">\r\n        									[field:title/]</a>\r\n        							</h3>\r\n					</li>\r\n					<li class=\"date\"><span>日期：</span>[field:pubdate function=\"GetDateMK(@me)\"/]\r\n</li>\r\n			   	</ul>\r\n			</div>\r\n			</li>\r\n		<li class=\"clearBoth\"></li>\r\n        ",23396,23861);
$z[9][4]['pagesize']="15";
$z[10]=Array("pagelist","",24196,24262);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",24497,24534);
$z[11][4]['filename']="footer.htm";

?>