<?php
$z[0]=Array("field","",305,324);
$z[0][4]['name']="title";
$z[1]=Array("global","",325,351);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",392,414);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",454,505);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",999,1036);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",1044,1082);
$z[5][4]['filename']="header2.htm";
$z[6]=Array("channel","\r\n<div class=\"list\">\r\n				\r\n				<div class=\"new-module\">\r\n					<h3>\r\n						<a title=\"[field:typename/]\" \r\n							href=\"[field:typeurl/]\" \r\n							target=\"_self\"\r\n							>[field:typename/]</a>\r\n					</h3>\r\n					<p class=\"summary\">\r\n					</p>\r\n					\r\n				</div>\r\n			</div>\r\n",1895,2205);
$z[6][4]['type']="son";
$z[7]=Array("include","",2310,2353);
$z[7][4]['filename']="sidebarslide.htm";
$z[8]=Array("field","",2726,2755);
$z[8][4]['name']="position";
$z[9]=Array("list"," \r\n            <li class=\"content column-num3\">\r\n					<div class=\"pic-module\">\r\n						<div class=\"pic\">\r\n									<a href=\"[field:arcurl/]\" \r\n										title=\"[field:title/]\" target=\"_self\">\r\n											<img src= \"[field:litpic/]\"  id= \"FrontProducts_list01-1434963925335_29\" alt= \"[field:title/]\" title= \"[field:title/]\" onerror= \"this.src='/templets/default/images/common/noimage.jpg'\" /></a>\r\n								</div>\r\n							</div>\r\n					<div class=\"pro-module\">\r\n						<ul class=\"basic\">\r\n							<li class=\"code\">\r\n									<h1>\r\n										<span>商品名称：</span>\r\n										<strong>\r\n											<a href=\"[field:arcurl/]\" \r\n												title=\"field:title/\"\r\n												target=\"_self\"\r\n												>\r\n												[field:title/]</a>\r\n										</strong>\r\n									</h1>\r\n									</li>\r\n								</ul>\r\n						<p class=\"buttonP\">\r\n							</p>\r\n						</div>\r\n				</li>\r\n          ",5189,6099);
$z[9][4]['pagesize']="6";
$z[10]=Array("pagelist","",6563,6629);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",7769,7806);
$z[11][4]['filename']="footer.htm";

?>