<?php
$z[0]=Array("field","",305,324);
$z[0][4]['name']="title";
$z[1]=Array("global","",325,351);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",392,414);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",454,505);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",991,1028);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",1036,1074);
$z[5][4]['filename']="header2.htm";
$z[6]=Array("type"," \r\n  <li >\r\n  		<a class=\"menu-text1 \" href=\"[field:typeurl/]\"  title=\"[field:typename/]\" >[field:typename/]</a></li>\r\n   ",1802,1947);
$z[7]=Array("include","",2049,2092);
$z[7][4]['filename']="sidebarslide.htm";
$z[8]=Array("field","",2485,2514);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n    \r\n    <li class=\"content column-num3\">\r\n    \r\n    \r\n    <div class=\"pic\">\r\n					<a href=\"[field:arcurl/]\"  title=\"[field:title/]\" target=\"_self\">\r\n                                <img src= \"[field:litpic/]\"  alt= \"[field:title/]\" title= \"[field:title/]\" /></a>\r\n	</div>\r\n	 \r\n            <div class=\"main\">\r\n				<div class=\"newstitle\">\r\n					<ul>\r\n						<li class=\"title\">\r\n							<h3>\r\n							<a href=\"[field:arcurl/]\"  title=\"field:title/\" target=\"_self\">\r\n												[field:title/]</a>\r\n										</h3>\r\n						</li>\r\n						</ul>\r\n				</div>\r\n				<div class=\"newslist\">\r\n					<ul>\r\n						</ul>\r\n				</div>\r\n				</div>\r\n      </li>\r\n	",9142,9823);
$z[9][4]['pagesize']="6";
$z[9][4]['col']="3";
$z[10]=Array("pagelist","",10194,10260);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",10491,10528);
$z[11][4]['filename']="footer.htm";

?>