<?php
$z[0]=Array("field","",305,324);
$z[0][4]['name']="title";
$z[1]=Array("global","",325,351);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",392,414);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",454,505);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",986,1023);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",1031,1069);
$z[5][4]['filename']="header2.htm";
$z[6]=Array("channel","\r\n							<li class=\"menu-none\"><a id=\"comContent2_13\" href=\"[field:typeurl/]\"  title=\"[field:typename/]\" class=\"menu-text1\" >[field:typename/]</a></li>\r\n							",2291,2489);
$z[6][4]['type']="son";
$z[7]=Array("include","",2603,2646);
$z[7][4]['filename']="sidebarslide.htm";
$z[8]=Array("field","",3824,3845);
$z[8][4]['name']="content";
$z[9]=Array("include","",4087,4124);
$z[9][4]['filename']="footer.htm";

?>